- hosts: all
  become: yes
  tasks:

    - name: Load SSH keys from user files
      include_vars:
        file: "{{ item }}"
      with_fileglob:
        - users/*.yaml
      register: loaded_users

    - name: Debug loaded user files
      debug:
        var: user_files

    - name: Create users based on file names
      user:
        name: "{{ item.path | basename | splitext | first }}"
        groups: "sudo"
        state: present
        shell: /bin/bash
      loop: "{{ user_files.files }}"
      tags: create_users

    - name: Allow users to run sudo without a password
      lineinfile:
        path: "/etc/sudoers"
        state: present
        line: "{{ item.path | basename | splitext | first }} ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"
      loop: "{{ user_files.files }}"
      tags: sudoers

    - name: Add SSH key for users
      authorized_key:
        user: "{{ item.path | basename | splitext | first }}"
        key: "{{ lookup('file', item.path) }}"
      loop: "{{ user_files.files }}"
      tags: add_ssh_keys
