- hosts: all
  become: yes
  tasks:
  
    - name: Loading SSH keys from user files
      find:
        paths: "./users"
        patterns: "*.yaml"
        recurse: yes
      register: user_files

    - name: Debuggin loaded user files
      debug:
        var: user_files

    - name: Creating users based on file names
      user:
        name: "{{ item.path | basename | regex_replace('.yaml', '') }}"
        state: present
        groups: "sudo"
        shell: /bin/bash
      loop: "{{ user_files.files }}"
      tags: create_users

    - name: Adding users to sudoers
      lineinfile:
        path: /etc/sudoers
        state: present
        line: "{{ item.path | basename | regex_replace('.yaml', '') }} ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"
      loop: "{{ user_files.files }}"
      tags: sudoers

    - name: Adding SSH keys for users
      authorized_key:
        user: "{{ item.path | basename | regex_replace('.yaml', '') }}"
        key: "{{ lookup('file', item.path) }}"
      loop: "{{ user_files.files }}"
      tags: add_ssh_keys
