- hosts: all
  become: yes
  tasks:

    - name: Downloading vars from users files
      include_vars:
        file: "{{ item }}"
      with_fileglob:
        - users/*.yaml
      register: loaded_users

    - name: Debug loaded users
      debug:
        var: loaded_users

    - name: Creating the users
      user:
        name: "{{ item.ansible_facts.loaded_user.name }}"
        groups: "{{ item.ansible_facts.loaded_user.groups | default('sudo') }}"
        state: present
        shell: /bin/bash
      loop: "{{ loaded_users.results }}"
      tags: create_users
      
    - name: Allow users to run sudo without a password
      lineinfile:
        path: /etc/sudoers
        line: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
        state: present
        validate: 'visudo -cf %s'
      loop: "{{ loaded_users.results }}"
      
    - name: Adding ssh keys for users
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ item.ssh_key }}"
      loop: "{{ loaded_users.results }}"
      tags: add_ssh_keys
