- hosts: all
  become: yes
  tasks:

    - name: Downloading vars from users files
      include_vars:
        file: "{{ item }}"
      loop: "{{ query('fileglob', lookup('env', 'WORKSPACE') + '/users/*.yaml') }}"
      register: loaded_users

    - name: Gathering the user list
      set_fact:
        users: "{{ loaded_users.results | map(attribute='ansible_facts') | list }}"
        
    - name: Creating the users
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups | default('sudo') }}"
        state: present
        shell: /bin/bash
      loop: "{{ users }}"
      tags: create_users
      
    - name: Allow users to run sudo without a password
      lineinfile:
        path: /etc/sudoers
        line: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
        state: present
        validate: 'visudo -cf %s'
      loop: "{{ users }}"
      
    - name: Add ssh key for users
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ item.ssh_key }}"
      loop: "{{ users }}"
      tags: add_ssh_keys
